### ISSUE TITLE
CPP Algorithm for Searching

### ISSUE THREAD

**Issue by siddharth25pandey** [siddharth25pandey/CPP-Programming#10]

**Comment by jatinjain001** [comment]
I would like to work on this issue ..

**Comment by siddharth25pandey** [comment]
> I would like to work on this issue ..

@jatinjain001 Go ahead
All the very best

**Comment by jatinjain001** [comment]
Brother, There is both of the searching algorithm is present , What i have to do then..

**Comment by siddharth25pandey** [comment]
@jatinjain001 You can work on remaining issues
