### ISSUE TITLE
CPP Algorithm for Sorting

### ISSUE THREAD

**Issue by siddharth25pandey** [siddharth25pandey/CPP-Programming#11]

**Comment by jatinjain001** [comment]
Please assign it to me ...

**Comment by srasti-0630** [comment]
Hi @siddharth25pandey, I would like to work on this, please assign it to me. Also, there's one more question which I would like to ask. All kinds of algorithms are to be included in single code file or different files, please clarify.

**Comment by siddharth25pandey** [comment]
@srasti-0630 All Algorithm of same type must be included in a Folder with different files.
Go ahead, I assigned you
All the very best.

**Comment by siddharth25pandey** [comment]
> Please assign it to me ...

@jatinjain001 Go ahead
All the very best

**Comment by srasti-0630** [comment]
> @srasti-0630 All Algorithm of same type must be included in a Folder with different files.
> Go ahead, I assigned you
> All the very best.

I saw that all the algorithms are already present in the sorting folder except a few like radix sort, and some algortihms recursive approach. I would like to add them to this folder. Should I go ahead?

**Comment by siddharth25pandey** [comment]
> > @srasti-0630 All Algorithm of same type must be included in a Folder with different files.
> > Go ahead, I assigned you
> > All the very best.
> 
> I saw that all the algorithms are already present in the sorting folder except a few like radix sort, and some algortihms recursive approach. I would like to add them to this folder. Should I go ahead?

@srasti-0630 Yeah you can, Also try to add the remaining ones
Thanks!

**Comment by jatinjain001** [comment]
bro can i work on this ,Cause the issue you assigned me was already completetd .?

**Comment by siddharth25pandey** [comment]
> bro can i work on this ,Cause the issue you assigned me was already completetd .?

Yeah go ahead
All the very best

**Comment by jatinjain001** [comment]
bro now all the algorithms of sorting is added ,If you want you can close this issue ..

**Comment by siddharth25pandey** [comment]
@jatinjain001 Yeah, thanks for informing

**Comment by srasti-0630** [comment]
A few remaining still you closed it .. can I add it ?

**Comment by srasti-0630** [comment]
Could you reopen it and review mine once then close it, please?
