### ISSUE TITLE
CPP Algorithm for Linked List

### ISSUE THREAD

**Issue by siddharth25pandey** [siddharth25pandey/CPP-Programming#13]

**Comment by anu725053** [comment]
i want to work on this.

**Comment by siddharth25pandey** [comment]
@anu725053 Go ahead
All the very best

**Comment by jatinjain001** [comment]
I want to work on this
 Can you please assign  it to me

**Comment by siddharth25pandey** [comment]
> I want to work on this
> Can you please assign it to me

@jatinjain001 Go ahead
All the best :+1:

**Comment by dhruvinfo28** [comment]
I also want to work on this , will you please assign it to me.

**Comment by siddharth25pandey** [comment]
> I also want to work on this , will you please assign it to me.

@dhruvinfo28 Go ahead
All the best :+1:

**Comment by jatinjain001** [comment]
I want to work on this please assign it to mee

**Comment by siddharth25pandey** [comment]
> I want to work on this please assign it to mee

Hava a look on previous comments, I had assigned you 10 days back.

**Comment by siddharth25pandey** [comment]
> I want to work on this please assign it to mee

Have a look on previous comments, I had assigned you 10 days back.

**Comment by jatinjain001** [comment]
Okay thank you ... I was thinking that I have to ask again .
