### ISSUE TITLE
Create a Proper Readme file

### ISSUE THREAD

**Issue by siddharth25pandey** [siddharth25pandey/CPP-Programming#27]
Create a Proper Readme file which consist of Contributors name ,picture, number of commits done, etc.

**Comment by NaveenBandarage** [comment]
Hey I added a pull request that I think might have sorted this please have a look!

**Comment by NaveenBandarage** [comment]
Added committers and number of commits sorry didn't mean to only add my own just did it as a template! :)

**Comment by siddharth25pandey** [comment]
> Added committers and number of commits sorry didn't mean to only add my own just did it as a template! :)

No worries, But I am accepting something [like](https://github.com/siddharth25pandey/CPP-Programming/blob/master/README.md)
