### ISSUE TITLE
Settle the scattered files into their respective folders

### ISSUE THREAD

**Issue by siddharth25pandey** [siddharth25pandey/CPP-Programming#30]
Please change the destination of files which are not present in any directory.
Place them accordingly

**Comment by jatinjain001** [comment]
bro i want to do  work on this issue

**Comment by siddharth25pandey** [comment]
> bro i want to do work on this issue

@jatinjain001 Go ahead

**Comment by jatinjain001** [comment]
I create a PR regarding this review it bro ...
