### ISSUE TITLE
CPP Algorithm for Trees

### ISSUE THREAD

**Issue by siddharth25pandey** [siddharth25pandey/CPP-Programming#34]
Implement various types of functionalities such as Insertion,Deletion,Searching,etc of different types of Trees

**Comment by uditswaroopa** [comment]
can you expand your Issue?

**Comment by siddharth25pandey** [comment]
> can you expand your Issue?

@uditswaroopa Have a look

**Comment by Manognya1000** [comment]
@siddharth25pandey I'd like to work on this.

**Comment by siddharth25pandey** [comment]
@Manognya1000 Go ahead

**Comment by shubhangi-singh21** [comment]
@siddharth25pandey I would like to add some tree traversal algorithm if you permit :)

**Comment by siddharth25pandey** [comment]
@shubhangi-singh21 Go ahead
All the very best

**Comment by shubhangi-singh21** [comment]
> @shubhangi-singh21 Go ahead
> All the very best

I added one file. Pls have a look update me on the same :)

**Comment by varunsharma21** [comment]
I would like to add solutions to some of frequently asked questions like inverting binary tree, constructing tree from inorder and postorder, etc.. If you allow.

**Comment by siddharth25pandey** [comment]
> I would like to add solutions to some of frequently asked questions like inverting binary tree, constructing tree from inorder and postorder, etc.. If you allow.

@varunsharma21 Go ahead
All the very best 👍
